<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class PlayersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $players = [
  ["name" => "Bernd Leno (Leverkusen)", "team_id" =>21],
["name" => "Manuel Neuer (Bayern)", "team_id" =>21],
["name" => "Marc-André ter Stegen (Barcelona)", "team_id" =>21],
["name" => "Kevin Trapp (PSG)", "team_id" =>21],
["name" => "Jerome Boateng (Bayern)", "team_id" =>21],
["name" => "Matthias Ginter (Gladbach)", "team_id" =>21],
["name" => "Jonas Hector (Colonia)", "team_id" =>21],
["name" => "Mats Hummels (Bayern)", "team_id" =>21],
["name" => "Joshua Kimmich (Bayern)", "team_id" =>21],
["name" => "Marvin Plattenhardt (Hertha)", "team_id" =>21],
["name" => "Antonio Rüdiger (Chelsea)", "team_id" =>21],
["name" => "Niklas Süle (Bayern)", "team_id" =>21],
["name" => "Jonathan Tah (Leverkusen)", "team_id" =>21],
["name" => "Julian Brandt (Leverkusen)", "team_id" =>21],
["name" => "Julian Draxler (PSG)", "team_id" =>21],
["name" => "Mario Gómez (Stuttgart)", "team_id" =>21],
["name" => "Leon Goretzka (Schalke)", "team_id" =>21],
["name" => "Ilkay Gündogan (Manchester City)", "team_id" =>21],
["name" => "Sami Khedira (Juventus)", "team_id" =>21],
["name" => "Toni Kroos (Real Madrid)", "team_id" =>21],
["name" => "Thomas Müller (Bayern)", "team_id" =>21],
["name" => "Mesut Özil (Arsenal)", "team_id" =>21],
["name" => "Nils Petersen (Friburgo)", "team_id" =>21],
["name" => "Marco Reus (Dortmund)", "team_id" =>21],
["name" => "Sebastian Rudy (Bayern)", "team_id" =>21],
["name" => "Leroy Sané (Manchester City)", "team_id" =>21],
["name" => "Timo Werner (RB Leipzig)", "team_id" =>21],
["name" => "Fawa Al Qarni (Al-Ittihad)", "team_id" =>2],
["name" => "Mohammed Al-Owais (Al-Ahli)", "team_id" =>2],
["name" => "Yasser Al-Mosailem (Al-Ahli)", "team_id" =>2],
["name" => "Abdullah Al-Muaiouf (Al-Hilal)", "team_id" =>2],
["name" => "Mansour Al-Harbi (Al-Ahli)", "team_id" =>2],
["name" => "Yasir Al-Shahrani (Al-Hilal)", "team_id" =>2],
["name" => "Mohammed Al-Burayk (Al-Hilal)", "team_id" =>2],
["name" => "Saeed Al-Mowalad (Al-Ahli)", "team_id" =>2],
["name" => "Motaz Hawsawi (Al-Ahli)", "team_id" =>2],
["name" => "Osama Hawsawi (Al-Hilal)", "team_id" =>2],
["name" => "Omar Hawsawi (Al-Nasr)", "team_id" =>2],
["name" => "Mohammed Jahfali (Al-Hilal)", "team_id" =>2],
["name" => "Ali Al-Boleahi (Al-Hilal)", "team_id" =>2],
["name" => "Abdullah Al-Khaibari (Al-Shabab)", "team_id" =>2],
["name" => "Abdelmalek Al-Khaibari (Al-Hilal)", "team_id" =>2],
["name" => "Abdullah Ateef (Al-Hilal)", "team_id" =>2],
["name" => "Taisir Al-Jassim (Al-Ahli)", "team_id" =>2],
["name" => "Hussein Al-Moghawi (Al-Ahli)", "team_id" =>2],
["name" => "Salman Al-Faraj (Al-Hilal)", "team_id" =>2],
["name" => "Nawaf Al-Abed (Al-Hilal)", "team_id" =>2],
["name" => "Mohamed Kanu (Al-Hilal)", "team_id" =>2],
["name" => "Hattan Bahbir (Al-Shabab)", "team_id" =>2],
["name" => "Mohamed Al-Kowaikaby", "team_id" =>2],
["name" => "Salem Al-Dawsari (Villarreal)", "team_id" =>2],
["name" => "Yahya Al-Shehri (Leganés)", "team_id" =>2],
["name" => "Fahad Al-Muwallad (Levante)", "team_id" =>2],
["name" => "Mohamed Al-Sahlawy (Al-Nasr)", "team_id" =>2],
["name" => "Muhannad Asiri (Al-Ahli)", "team_id" =>2],
["name" => "Sergio Romero (Manchester United)", "team_id" =>13],
["name" => "Wilfredo Caballero (Chelsea)", "team_id" =>13],
["name" => "Franco Armani (River)", "team_id" =>13],
["name" => "Nahuel Guzmán (Tigres)", "team_id" =>13],
["name" => "Gabriel Mercado (Sevilla)", "team_id" =>13],
["name" => "Eduardo Salvio (Benfica)", "team_id" =>13],
["name" => "Federico Fazio (Roma)", "team_id" =>13],
["name" => "Nicolás Otamendi (Manchester City)", "team_id" =>13],
["name" => "Marcos Acuña (Sporting de Lisboa)", "team_id" =>13],
["name" => "Nicolás Tagliafico (Ajax)", "team_id" =>13],
["name" => "Marcos Rojo (Manchester United)", "team_id" =>13],
["name" => "Ramiro Funes Mori (Everton)", "team_id" =>13],
["name" => "Javier Mascherano (Hebei Fortune)", "team_id" =>13],
["name" => "Germán Pezzella (Fiorentina)", "team_id" =>13],
["name" => "Cristian Ansaldi (Torino)", "team_id" =>13],
["name" => "Manuel Lanzini (West Ham)", "team_id" =>13],
["name" => "Lucas Biglia (Milan)", "team_id" =>13],
["name" => "Giovani Lo Celso (PSG)", "team_id" =>13],
["name" => "Ángel Di María (PSG)", "team_id" =>13],
["name" => "Guido Pizarro (Sevilla)", "team_id" =>13],
["name" => "Éver Banega (Sevilla)", "team_id" =>13],
["name" => "Leandro Paredes (Zenit San Petersburgo)", "team_id" =>13],
["name" => "Enzo Pérez (River)", "team_id" =>13],
["name" => "Rodrigo Battaglia (Sporting de Lisboa)", "team_id" =>13],
["name" => "Pablo Pérez (Boca)", "team_id" =>13],
["name" => "Maximiliano Meza (Independiente)", "team_id" =>13],
["name" => "Ricardo Centurión (Racing)", "team_id" =>13],
["name" => "Cristian Pavón (Boca)", "team_id" =>13],
["name" => "Lionel Messi (Barcelona)", "team_id" =>13],
["name" => "Paulo Dybala (Juventus)", "team_id" =>13],
["name" => "Sergio Agüero (Manchester City)", "team_id" =>13],
["name" => "Gonzalo Higuaín (Juventus)", "team_id" =>13],
["name" => "Diego Perotti (Roma)", "team_id" =>13],
["name" => "Mauro Icardi (Inter)", "team_id" =>13],
["name" => "Lautaro Martínez (Racing)", "team_id" =>13],
["name" => "Mat Ryan (Brighton)", "team_id" =>10],
["name" => "Brad Jones (Feyenoord)", "team_id" =>10],
["name" => "Danny Vukovic (Genk)", "team_id" =>10],
["name" => "Trent Sainsbury (Grasshoppers)", "team_id" =>10],
["name" => "Matthew Jurman (Suwon)", "team_id" =>10],
["name" => "Milos Degenek (Yokohama Marinos)", "team_id" =>10],
["name" => "Joshua Risdon (Western Sydney Wanderers)", "team_id" =>10],
["name" => "Aziz Behich (Bursaspor)", "team_id" =>10],
["name" => "James Meredith (Millwall)", "team_id" =>10],
["name" => "Fran Karacic (NK Lokomotiva)", "team_id" =>10],
["name" => "Mile Jedinak (Aston Villa)", "team_id" =>10],
["name" => "Aaron Mooy (Huddersfield)", "team_id" =>10],
["name" => "Tom Rogic (Celtic)", "team_id" =>10],
["name" => "Massimo Luongo (QPR)", "team_id" =>10],
["name" => "Jackson Irvine (Hull City)", "team_id" =>10],
["name" => "Joshua Brillante (Sydney FC)", "team_id" =>10],
["name" => "Dimi Petratos (Newcastle Jets)", "team_id" =>10],
["name" => "Mark Milligan (Al Ahli).", "team_id" =>10],
["name" => "Tim Cahill (Millwall)", "team_id" =>10],
["name" => "Tomi Juric (FC Luzern)", "team_id" =>10],
["name" => "Mathew Leckie (Hertha Berlin)", "team_id" =>10],
["name" => "James Troisi (Melbourne Victory)", "team_id" =>10],
["name" => "Daniel Arzani (Melbourne City)", "team_id" =>10],
["name" => "Andrew Nabbout (Urawa Red Diamonds)", "team_id" =>10],
["name" => "Nikita Rukavytsya (Maccabi Haifa)", "team_id" =>10],
["name" => "Robbie Kruse (Bochum)", "team_id" =>10],
["name" => "Alisson (Roma)", "team_id" =>17],
["name" => "Ederson (Manchester City)", "team_id" =>17],
["name" => "Cassio (Corinthians)", "team_id" =>17],
["name" => "Miranda (Inter de Milán)", "team_id" =>17],
["name" => "Marquinhos (PSG)", "team_id" =>17],
["name" => "Thiago Silva (PSG)", "team_id" =>17],
["name" => "Geromel (Grêmio)", "team_id" =>17],
["name" => "Marcelo (Real Madrid)", "team_id" =>17],
["name" => "Filipe Luis (Atlético)", "team_id" =>17],
["name" => "Fagner (Corinthians)", "team_id" =>17],
["name" => "Danilo (Manchester City)", "team_id" =>17],
["name" => "Casemiro (Real Madrid)", "team_id" =>17],
["name" => "Paulinho (Barcelona)", "team_id" =>17],
["name" => "Fernandinho (Manchester City)", "team_id" =>17],
["name" => "Fred (Shakhtar Donetsk)", "team_id" =>17],
["name" => "Renato Augusto (Beijing Guoan)", "team_id" =>17],
["name" => "Willian (Chelsea)", "team_id" =>17],
["name" => "Coutinho (Barcelona)", "team_id" =>17],
["name" => "Neymar (PSG)", "team_id" =>17],
["name" => "Gabriel Jesus (Manchester City)", "team_id" =>17],
["name" => "Firmino (Liverpool)", "team_id" =>17],
["name" => "Douglas Costa (Juventus)", "team_id" =>17],
["name" => "Taison (Shakhtar Donetsk)", "team_id" =>17],
["name" => "Iván Arboleda (Banfield)", "team_id" =>31],
["name" => "José Fernando Cuadrado (Once Caldas)", "team_id" =>31],
["name" => "David Ospina (Arsenal)", "team_id" =>31],
["name" => "Camilo Vargas (Deportivo Cali)", "team_id" =>31],
["name" => "Santiago Arias (PSV)", "team_id" =>31],
["name" => "Farid Díaz (Olimpia)", "team_id" =>31],
["name" => "Bernardo Espinosa (Girona)", "team_id" =>31],
["name" => "Frank Fabra (Boca Juniors)", "team_id" =>31],
["name" => "Stefan Medina (Monterrey)", "team_id" =>31],
["name" => "Yerry Mina (Barcelona)", "team_id" =>31],
["name" => "Johan Mojica (Girona)", "team_id" =>31],
["name" => "Óscar Murillo (Pachuca)", "team_id" =>31],
["name" => "Davinson Sánchez (Tottenham)", "team_id" =>31],
["name" => "William Tesillo (León)", "team_id" =>31],
["name" => "Cristian Zapata (Milán)", "team_id" =>31],
["name" => "Abel Aguilar (Deportivo Cali)", "team_id" =>31],
["name" => "Wílmar Barrios (Boca Juniors)", "team_id" =>31],
["name" => "Edwin Cardona (Boca Juniors)", "team_id" =>31],
["name" => "Juan Guillermo Cuadrado (Juventus)", "team_id" =>31],
["name" => "Gustavo Cuéllar (Flamengo)", "team_id" =>31],
["name" => "Jefferson Lerma (Levante)", "team_id" =>31],
["name" => "Giovanni Moreno (Shangai Shenhua)", "team_id" =>31],
["name" => "Sebastián Pérez (Boca Juniors)", "team_id" =>31],
["name" => "Juan Fernando Quintero (River Plate)", "team_id" =>31],
["name" => "James Rodríguez (Bayern Múnich)", "team_id" =>31],
["name" => "Carlos Sánchez (Espanyol)", "team_id" =>31],
["name" => "Mateus Uribe (América)", "team_id" =>31],
["name" => "Carlos Bacca (Villarreal)", "team_id" =>31],
["name" => "Miguel Borja (Palmeiras)", "team_id" =>31],
["name" => "Yimmi Chará (Junior)", "team_id" =>31],
["name" => "Radamel Falcao García (Mónaco)", "team_id" =>31],
["name" => "Teófilo Gutiérrez (Junior)", "team_id" =>31],
["name" => "José Heriberto Izquierdo (Brighton)", "team_id" =>31],
["name" => "Luis Fernando Muriel (Sevilla)", "team_id" =>31],
["name" => "Duván Zapata (Sampdoria)", "team_id" =>31],
["name" => "Kim Seung-gyu (Vissel Kobe)", "team_id" =>24],
["name" => "Kim Jin-hyeon (Cerezo Osaka)", "team_id" =>24],
["name" => "Cho Hyun-woo (Daegu FC)", "team_id" =>24],
["name" => "Kim young-gwon (Guangzhou Evergrande)", "team_id" =>24],
["name" => "Jang Hyun-soo (FC Tokyo)", "team_id" =>24],
["name" => "Jung Seung-hyun (Sagan Tosu)", "team_id" =>24],
["name" => "Yun Yong-sun (Seongnam FC)", "team_id" =>24],
["name" => "Kwon Kyung-won (Tianjin Quanjian)", "team_id" =>24],
["name" => "Oh Ban-suk (Jeju United)", "team_id" =>24],
["name" => "Kim Jin-su (Jeonbuk Hyundai Motors)", "team_id" =>24],
["name" => "Kim Min-woo (Sangju Sangmu)", "team_id" =>24],
["name" => "Park Joo-ho (Ulsan Hyundai)", "team_id" =>24],
["name" => "Hong Chul (Sangju Sangmu)", "team_id" =>24],
["name" => "Lee Yong (Jeonbuk Hyundai Motors)", "team_id" =>24],
["name" => "Go Yo-han (FC Seoul)", "team_id" =>24],
["name" => "Ki Sung-yueng (Swansea City)", "team_id" =>24],
["name" => "Jung Woo-young (Vissel Kobe)", "team_id" =>24],
["name" => "Kwon Chang-hoon (Dijon)", "team_id" =>24],
["name" => "Ju Se-jong (Asan Mugunghwa)", "team_id" =>24],
["name" => "Koo Ja-cheol (Augsburgo)", "team_id" =>24],
["name" => "Lee Jae-sung (Jeonbuk Hyundai Motors)", "team_id" =>24],
["name" => "Lee Seung-woo (Hellas Verona)", "team_id" =>24],
["name" => "Lee Chung-yong (Crystal Palace)", "team_id" =>24],
["name" => "Moon Seon-min (Incheon United)", "team_id" =>24],
["name" => "Kim Shin-wook (Jeonbuk Hyundai Motors)", "team_id" =>24],
["name" => "Son Heung-min (Tottenham Hotspur)", "team_id" =>24],
["name" => "Lee Keun-ho (Gangwon FC)", "team_id" =>24],
["name" => "Hwang Hee-chan (Salzburgo)", "team_id" =>24],
["name" => "Keylor Navas (Real Madrid)", "team_id" =>19],
["name" => "Patrick Pemberton (Alajuanense)", "team_id" =>19],
["name" => "Leonel Moreira (Herediano)", "team_id" =>19],
["name" => "Cristian Gamboa (Celtic)", "team_id" =>19],
["name" => "Ian Smith (Norrköping)", "team_id" =>19],
["name" => "Ronald Matarrita (New York City FC)", "team_id" =>19],
["name" => "Bryan Oviedo (Sunderland)", "team_id" =>19],
["name" => "Óscar Duarte (Espanyol)", "team_id" =>19],
["name" => "Giancarlo González (Bolonia)", "team_id" =>19],
["name" => "Francisco Calvo (Minnesota United)", "team_id" =>19],
["name" => "Kendall Watson (Vancouver Whitecaps)", "team_id" =>19],
["name" => "Johnny Acosta (Águilas Doradas)", "team_id" =>19],
["name" => "David Guzmán (Portland Timbers)", "team_id" =>19],
["name" => "Yeltsin Tejeda (Lausanne)", "team_id" =>19],
["name" => "Celso Borges (Deportivo La Coruña)", "team_id" =>19],
["name" => "Randall Azofeifa (Herediano)", "team_id" =>19],
["name" => "Rooney Wallace (New York City FC)", "team_id" =>19],
["name" => "Bryan Ruiz (Sporting de Lisboa)", "team_id" =>19],
["name" => "Daniel Colindres (Saprissa)", "team_id" =>19],
["name" => "Christian Bolaños (Saprissa)", "team_id" =>19],
["name" => "Johan Venegas (Saprissa)", "team_id" =>19],
["name" => "Joel Campbell (Betis)", "team_id" =>19],
["name" => "Marco Ureña (Los Angeles FC)", "team_id" =>19],
["name" => "Danijel Subasic (Mónaco)", "team_id" =>15],
["name" => "Lovre Kalinic (Gante)", "team_id" =>15],
["name" => "Dominik Livakovic (Dinamo Zagreb)", "team_id" =>15],
["name" => "Vedran Corluka (Lokomotiv Moscou)", "team_id" =>15],
["name" => "Domagoj Vida (Besiktas)", "team_id" =>15],
["name" => "Ivan Strinic (Sampdoria)", "team_id" =>15],
["name" => "Dejan Lovren (Liverpool)", "team_id" =>15],
["name" => "Sime Vrsaljko (Atlético de Madrid)", "team_id" =>15],
["name" => "Josip Pivaric (Dinamo Kiev)", "team_id" =>15],
["name" => "Tin Jedvaj (Bayer Leverkusen)", "team_id" =>15],
["name" => "Matej Mitrovic (Brujas)", "team_id" =>15],
["name" => "Duje Caleta-Car (Salzburgo)", "team_id" =>15],
["name" => "Luka Modric (Real Madrid)", "team_id" =>15],
["name" => "Mateo Kovacic (Real Madrid)", "team_id" =>15],
["name" => "Ivan Rakitic (Barcelona)", "team_id" =>15],
["name" => "Milan Badelj (Fiorentina)", "team_id" =>15],
["name" => "Marcelo Brozovic (Inter)", "team_id" =>15],
["name" => "Filip Bradaric (Rijeka)", "team_id" =>15],
["name" => "Mario Mandzukic (Juventus)", "team_id" =>15],
["name" => "Ivan Perisic (Inter)", "team_id" =>15],
["name" => "Nikola Kalinic (Milán)", "team_id" =>15],
["name" => "Andrej Kramaric (Hoffenheim)", "team_id" =>15],
["name" => "Marko Pjaca (Schalke)", "team_id" =>15],
["name" => "Ante Rebic (Eintracht Fráncfort)", "team_id" =>15],
["name" => "Frederik Rønnow (Brondby)", "team_id" =>12],
["name" => "Jesper Hansen (Midtjylland)", "team_id" =>12],
["name" => "Jonas Lössl (Huddersfield Town)", "team_id" =>12],
["name" => "Kasper Schmeichel (Leicester City)", "team_id" =>12],
["name" => "Andreas Bjelland (Brentford)", "team_id" =>12],
["name" => "Andreas Christensen (Chelsea)", "team_id" =>12],
["name" => "Henrik Dalsgaard (Brentford)", "team_id" =>12],
["name" => "Jannik Vestergaard (Borussia Mönchengladbach)", "team_id" =>12],
["name" => "Jens Stryger Larsen (Udinese)", "team_id" =>12],
["name" => "Jonas Knudsen (Ipswich Town)", "team_id" =>12],
["name" => "Mathias 'Zanka' Jørgensen (Huddersfield Town)", "team_id" =>12],
["name" => "Nicolai Boilesen (København)", "team_id" =>12],
["name" => "Peter Ankersen (København)", "team_id" =>12],
["name" => "Riza Durmisi (Real Betis)", "team_id" =>12],
["name" => "Simon Kjær (Sevilla)", "team_id" =>12],
["name" => "Christian Eriksen (Tottenham Hotspur)", "team_id" =>12],
["name" => "Daniel Wass (Celta)", "team_id" =>12],
["name" => "Lasse Schöne (Ajax)", "team_id" =>12],
["name" => "Lukas Lerager (Girondins)", "team_id" =>12],
["name" => "Mathias Jensen (Nordsjælland)", "team_id" =>12],
["name" => "Michael Krohn-Dehli (Deportivo)", "team_id" =>12],
["name" => "Mike Jensen (Rosenborg)", "team_id" =>12],
["name" => "Pierre Emile Højbjerg (Southampton)", "team_id" =>12],
["name" => "Thomas Delaney (Werder Bremen)", "team_id" =>12],
["name" => "William Vitved Kvist (København)", "team_id" =>12],
["name" => "Andreas Cornelius (Atalanta)", "team_id" =>12],
["name" => "Kasper Dolberg (Ajax)", "team_id" =>12],
["name" => "Kenneth Zohore (Cardiff City)", "team_id" =>12],
["name" => "Martin C. Braithwaite (Girondins)", "team_id" =>12],
["name" => "Nicklas Bendtner (Rosenborg)", "team_id" =>12],
["name" => "Nicolai Jørgensen (Feyenoord)", "team_id" =>12],
["name" => "Pione Sisto (Celta)", "team_id" =>12],
["name" => "Robert Skov (København)", "team_id" =>12],
["name" => "Viktor Fischer (København)", "team_id" =>12],
["name" => "Yussuf Yurary Poulsen (RB Leipzig)", "team_id" =>12],
["name" => "Essam El-Hadary (Al Taawoun)", "team_id" =>3],
["name" => "Mohamed El-Shennawy (Al Ahly)", "team_id" =>3],
["name" => "Sherif Ekramy (Al Ahly)", "team_id" =>3],
["name" => "Mohamed Awaad (Ismaily)", "team_id" =>3],
["name" => "Ahmed Fathy (Al Ahly)", "team_id" =>3],
["name" => "Saad Samir (Al Ahly)", "team_id" =>3],
["name" => "Ayman Ashraf (Al Ahly)", "team_id" =>3],
["name" => "Mahmoud Hamdy (Zamalek)", "team_id" =>3],
["name" => "Mohamed Abdelshafy (Al Fath)", "team_id" =>3],
["name" => "Ahmed Hegazy (West Brom)", "team_id" =>3],
["name" => "Aly Gabr (West Brom)", "team_id" =>3],
["name" => "Ahmed Elmohamady (Aston Villa)", "team_id" =>3],
["name" => "Karim Hafez (RC Lens)", "team_id" =>3],
["name" => "Omar Gaber (LAFC)", "team_id" =>3],
["name" => "Amro Tarek (Orlando City)", "team_id" =>3],
["name" => "Tarek Hamed (Zamalek)", "team_id" =>3],
["name" => "Mahmoud Abdelaziz (Zamalek)", "team_id" =>3],
["name" => "Abdalla El-Said (KuPS)", "team_id" =>3],
["name" => "Sam Moursy (Wigan)", "team_id" =>3],
["name" => "Mohamed Elneny (Arsenal)", "team_id" =>3],
["name" => "Ramdan Sobhy (Stoke City)", "team_id" =>3],
["name" => "Amr Warda (Atromitos)", "team_id" =>3],
["name" => "Mahmoud Abdelmoniem", "team_id" =>3],
["name" => "Mahmoud Ibrahim", "team_id" =>3],
["name" => "Mahmoud Abdelrazek", "team_id" =>3],
["name" => "Marwan Mohsen (Al Ahly)", "team_id" =>3],
["name" => "Ahmed Goma (Al Masry)", "team_id" =>3],
["name" => "Mohamed Salah (Liverpool)", "team_id" =>3],
["name" => "Ahmed Hassan (SC Braga)", "team_id" =>3],
["name" => "Alphonse Areola (PSG)", "team_id" =>9],
["name" => "Hugo Lloris (Tottenham)", "team_id" =>9],
["name" => "Steve Mandanda (Olympique de Marsella)", "team_id" =>9],
["name" => "Lucas Hernández (Atlético)", "team_id" =>9],
["name" => "Presnel Kimpembé (PSG)", "team_id" =>9],
["name" => "Benjamin Mendy (Manchester City)", "team_id" =>9],
["name" => "Raphäel Varane (Real Madrid)", "team_id" =>9],
["name" => "Adil Rami (Olympique de Marsella)", "team_id" =>9],
["name" => "Samuel Umtiti (Barcelona)", "team_id" =>9],
["name" => "Djibril Sidibé (Mónaco)", "team_id" =>9],
["name" => "Benjamin Pavard (Stuttgart)", "team_id" =>9],
["name" => "N'Golo Kanté (Chelsea)", "team_id" =>9],
["name" => "Blase Matuidi (Juventus)", "team_id" =>9],
["name" => "Steven N'Zonzi (Sevilla)", "team_id" =>9],
["name" => "Paul Pogba (Manchester United)", "team_id" =>9],
["name" => "Corentin Tolisso (Bayern de Múnich)", "team_id" =>9],
["name" => "Kylian Mbappé (PSG)", "team_id" =>9],
["name" => "Ousmane Dembelé (Barcelona)", "team_id" =>9],
["name" => "Thomas Lemar (Mónaco)", "team_id" =>9],
["name" => "Florian Thauvin (Olympique de Marsella)", "team_id" =>9],
["name" => "Antoine Griezmann (Atlético de Madrid)", "team_id" =>9],
["name" => "Olivier Giroud (Chelsea)", "team_id" =>9],
["name" => "Nabil Fekir (Olympique de Lyon)", "team_id" =>9],
["name" => "Jack Butland (Stoke)", "team_id" =>28],
["name" => "Jordan Pickford (Everton)", "team_id" =>28],
["name" => "Nick Pope (Burnley)", "team_id" =>28],
["name" => "Trent Alexander-Arnold (Liverpool)", "team_id" =>28],
["name" => "Gary Cahill (Chelsea)", "team_id" =>28],
["name" => "Fabian Delph (Manchester CIty)", "team_id" =>28],
["name" => "Phil Jones (Manchester United)", "team_id" =>28],
["name" => "Harry Maguire (Leicester)", "team_id" =>28],
["name" => "Danny Rose (Tottenham)", "team_id" =>28],
["name" => "John Stones (Manchester City)", "team_id" =>28],
["name" => "Kieran Trippier (Tottenham)", "team_id" =>28],
["name" => "Kyle Walker (Manchester City)", "team_id" =>28],
["name" => "Ashley Young (Manchester United)", "team_id" =>28],
["name" => "Dele Alli (Tottenham)", "team_id" =>28],
["name" => "Eric Dier (Tottenham)", "team_id" =>28],
["name" => "Jordan Henderson (Liverpool)", "team_id" =>28],
["name" => "Jesse Lingard (Manchester United)", "team_id" =>28],
["name" => "Ruben Loftus-Cheek (Chelsea)", "team_id" =>28],
["name" => "Harry Kane (Tottenham)", "team_id" =>28],
["name" => "Marcus Rashford (Manchester United)", "team_id" =>28],
["name" => "Raheem Sterling (Manchester City)", "team_id" =>28],
["name" => "Jamie Vardy (Leicester)", "team_id" =>28],
["name" => "Danny Welbeck (Arsenal)", "team_id" =>28],
["name" => "Alireza Beiranvand (Persepolis)", "team_id" =>8],
["name" => "Seyed Hossein Hosseini (Esteghlal)", "team_id" =>8],
["name" => "Rashid Mazaheri (Zob Ahan)", "team_id" =>8],
["name" => "Amir Abedzadeh (Maritimo)", "team_id" =>8],
["name" => "Ramin Rezaeian (Ostende)", "team_id" =>8],
["name" => "Voria Ghafouri", "team_id" =>8],
["name" => "Pejman Montazeri", "team_id" =>8],
["name" => "Seyed Majid Hosseini", "team_id" =>8],
["name" => "Omid Norafkan", "team_id" =>8],
["name" => "Roozbeh Cheshmi (Esteghlal)", "team_id" =>8],
["name" => "Steven Beitashour (Los Angeles FC)", "team_id" =>8],
["name" => "Seyed Jalal Hosseini", "team_id" =>8],
["name" => "Mohammad Ansari (Persepolis)", "team_id" =>8],
["name" => "Mohammad Reza Khanzadeh (Padideh)", "team_id" =>8],
["name" => "Morteza Pouraliganji (Alsaad)", "team_id" =>8],
["name" => "Milad Mohammadi (Akhmat Grozny)", "team_id" =>8],
["name" => "Saeid AGhaei (Sepahan)", "team_id" =>8],
["name" => "Saeid Ezatolahi (Amkar Perm)", "team_id" =>8],
["name" => "Masoud Shojaei (AEK Atenas)", "team_id" =>8],
["name" => "Ahmad Abdolahzadeh (Foolad)", "team_id" =>8],
["name" => "Saman Ghoddos (Ostersunds)", "team_id" =>8],
["name" => "Mahdi Torabi", "team_id" =>8],
["name" => "Ali Gholizadeh (Saipa)", "team_id" =>8],
["name" => "Ashkan Dejagah (Notthingham Forest)", "team_id" =>8],
["name" => "Omid Ebrahimi (Esteghlal)", "team_id" =>8],
["name" => "Ehsan Hajsafi (Olympiacos)", "team_id" =>8],
["name" => "Ali Karimi (Sepahan)", "team_id" =>8],
["name" => "Soroush Rafiei (Al Khor)", "team_id" =>8],
["name" => "Vahid Amiri (Persepolis)", "team_id" =>8],
["name" => "Alireza Jahanbakhsh (AZ Alkmaar)", "team_id" =>8],
["name" => "Karim Ansarifard (Olympiacos)", "team_id" =>8],
["name" => "Mahdi Taremi (Al Gharafa)", "team_id" =>8],
["name" => "Sardar Azmoun (Rubin Kazan)", "team_id" =>8],
["name" => "Reza Ghoochannejhad (Heerenveen)", "team_id" =>8],
["name" => "Kaveh Rezaei (Charleroi)", "team_id" =>8],
["name" => "Hannes Þór Halldórsson (Randers)", "team_id" =>14],
["name" => "Rúnar Alex Rúnarsson (Nordsjælland)", "team_id" =>14],
["name" => "Frederik Schram (Roskilde)", "team_id" =>14],
["name" => "Ari Freyr Skúlason (Lokeren)", "team_id" =>14],
["name" => "Hörður B. Magnússon (Bristol City)", "team_id" =>14],
["name" => "Ragnar Sigurðsson (Rostov)", "team_id" =>14],
["name" => "Kári Árnason (Aberdeen)", "team_id" =>14],
["name" => "Hólmar Örn Eyjólfsson (Levski Sofia)", "team_id" =>14],
["name" => "Sverrir Ingi Ingason (Rostov)", "team_id" =>14],
["name" => "Birkir Már Sævarsson (Valur)", "team_id" =>14],
["name" => "Samúel Kári Friðjónsson (Valerenga)", "team_id" =>14],
["name" => "Gylfi Sigurðsson (Everton)", "team_id" =>14],
["name" => "Aron Einar Gunnarsson (Cardiff City)", "team_id" =>14],
["name" => "Emil Hallfreðsson (Udinese)", "team_id" =>14],
["name" => "Birkir Bjarnason (Aston Villa)", "team_id" =>14],
["name" => "Jóhann Berg Guðmundsson (Burnley)", "team_id" =>14],
["name" => "Ólafur Ingi Skúlason (Karabukspor)", "team_id" =>14],
["name" => "Arnór Ingvi Traustason (Malmö)", "team_id" =>14],
["name" => "Rúrik Gíslason (Sandhausen)", "team_id" =>14],
["name" => "Alfreð Finnbogason (Augsburg)", "team_id" =>14],
["name" => "Björn Bergmann Sigurðarson (Rostov)", "team_id" =>14],
["name" => "Jón Daði Böðvarsson (Reading)", "team_id" =>14],
["name" => "Albert Guðmundsson (PSV)", "team_id" =>14],
["name" => "Eiji Kawashima (Metz)", "team_id" =>32],
["name" => "Masaaki Higashiguchi (Gamba Osaka)", "team_id" =>32],
["name" => "Kosuke Nakamura (Kashiwa Reysol)", "team_id" =>32],
["name" => "Yuto Nagatomo (Galatasaray)", "team_id" =>32],
["name" => "Tomoaki Makino (Urawa Red Diamonds)", "team_id" =>32],
["name" => "Maya Yoshida (Southampton)", "team_id" =>32],
["name" => "Hiroki Sakai (Marsella)", "team_id" =>32],
["name" => "Gotoku Sakai (Hamburgo)", "team_id" =>32],
["name" => "Gen Shoji (Kashima Antlers)", "team_id" =>32],
["name" => "Wataru Endo (Urawa Red Diamonds)", "team_id" =>32],
["name" => "Naomichi Ueda (Kashima Antlers)", "team_id" =>32],
["name" => "Makoto Hasebe (Eintracht)", "team_id" =>32],
["name" => "Toshihiro Aoyama (Sanfrecce Hiroshima)", "team_id" =>32],
["name" => "Keisuke Honda (Pachuca)", "team_id" =>32],
["name" => "Takashi Inui (Eibar)", "team_id" =>32],
["name" => "Shinji Kagawa (Dortmund)", "team_id" =>32],
["name" => "Hotaru Yamaguchi (Cerezo Osaka)", "team_id" =>32],
["name" => "Genki Haraguchi (Fortuna Düsseldorf)", "team_id" =>32],
["name" => "Takashi Usami (Fortuna Düsseldorf)", "team_id" =>32],
["name" => "Gaku Shibasaki (Getafe)", "team_id" =>32],
["name" => "Ryota Ohshima (Kawasaki Frontale)", "team_id" =>32],
["name" => "Kento Misao (Kashima Antlers)", "team_id" =>32],
["name" => "Yosuke Ideguchi (Cultural Leonesa)", "team_id" =>32],
["name" => "Shinji Okazaki (Leicester)", "team_id" =>32],
["name" => "Yuya Osako (Colonia)", "team_id" =>32],
["name" => "Yoshinori Muto (Mainz)", "team_id" =>32],
["name" => "Takuma Asano (Stuttgart)", "team_id" =>32],
["name" => "Munir (Numancia)", "team_id" =>7],
["name" => "Bono (Girona)", "team_id" =>7],
["name" => "Ahmed Reda Tagnaouti (IRT Tánger)", "team_id" =>7],
["name" => "Mehdi Benatia (Juventus)", "team_id" =>7],
["name" => "Romain Saiss (Wolverhampton)", "team_id" =>7],
["name" => "Manuel Da Costa (Basaksehir)", "team_id" =>7],
["name" => "Badr Benoun (Raja Casablanca)", "team_id" =>7],
["name" => "Nabil Dirar (Fenerbahce)", "team_id" =>7],
["name" => "Achraf Hakimi (Real Madrid)", "team_id" =>7],
["name" => "Hamza Mendyl (Lille)", "team_id" =>7],
["name" => "Mbark Boussoufa (Al Jazira)", "team_id" =>7],
["name" => "Karim El Ahmadi (Feyenoord)", "team_id" =>7],
["name" => "Youssef Ait Bennasser (Caen)", "team_id" =>7],
["name" => "Sofian Amrabat (Feyenoord)", "team_id" =>7],
["name" => "Younes Belhanda (Galatasaray)", "team_id" =>7],
["name" => "Fayçal Fajr (Getafe)", "team_id" =>7],
["name" => "Amine Harit (Schalke 04)", "team_id" =>7],
["name" => "Khalid Boutaib (Malatyaspor)", "team_id" =>7],
["name" => "Aziz Bouhaddouz (Saint Pauli)", "team_id" =>7],
["name" => "Ayoub El Kaabi (RSB Berkane)", "team_id" =>7],
["name" => "Nordin Amrabat (Leganés)", "team_id" =>7],
["name" => "Hakim Ziyech (Ajax)", "team_id" =>7],
["name" => "Mehdi Carcela (Standard Lieja)", "team_id" =>7],
["name" => "Guillermo Ochoa (Standard Lieja)", "team_id" =>22],
["name" => "Alfredo Talavera (Toluca)", "team_id" =>22],
["name" => "Jesús Corona (Cruz Azul)", "team_id" =>22],
["name" => "Carlos Salcedo (Eintracht Frankfurt)", "team_id" =>22],
["name" => "Néstor Araujo (Santos Laguna)", "team_id" =>22],
["name" => "Diego Reyes (Porto)", "team_id" =>22],
["name" => "Héctor Moreno (Real Sociedad)", "team_id" =>22],
["name" => "Hugo Ayala (Tigres)", "team_id" =>22],
["name" => "Oswaldo Alanís (Chivas)", "team_id" =>22],
["name" => "Edson Álvarez (América)", "team_id" =>22],
["name" => "Jesús Gallardo (Pumas UNAM)", "team_id" =>22],
["name" => "Miguel Layún (Sevilla)", "team_id" =>22],
["name" => "Jesús Molina (Monterrey)", "team_id" =>22],
["name" => "Rafael Márquez (retirado)", "team_id" =>22],
["name" => "Héctor Herrera (Porto)", "team_id" =>22],
["name" => "Jonathan dos Santos (LA Galaxy)", "team_id" =>22],
["name" => "Andrés Guardado (Betis)", "team_id" =>22],
["name" => "Erick Gutiérrez (Pachuca)", "team_id" =>22],
["name" => "Marco Fabián (Eintracht Frankfurt)", "team_id" =>22],
["name" => "Giovani dos Santos (LA Galaxy)", "team_id" =>22],
["name" => "Javier Hernández (West Ham United)", "team_id" =>22],
["name" => "Raúl Jiménez (Benfica)", "team_id" =>22],
["name" => "Oribe Peralta (América)", "team_id" =>22],
["name" => "Jesús Manuel Corona (Porto)", "team_id" =>22],
["name" => "Carlos Vela (Los Angeles FC)", "team_id" =>22],
["name" => "Javier Aquino (Tigres)", "team_id" =>22],
["name" => "Hirving Lozano (PSV Eindhoven)", "team_id" =>22],
["name" => "Jürgen Damm (Tigres)", "team_id" =>22],
["name" => "Ikechukwu Ezenwa", "team_id" =>16],
["name" => "Daniel Akpeyi", "team_id" =>16],
["name" => "Francis Uzoho", "team_id" =>16],
["name" => "Dele Ajiboye", "team_id" =>16],
["name" => "William Ekong", "team_id" =>16],
["name" => "Leon Balogun", "team_id" =>16],
["name" => "Olaoluwa Aina", "team_id" =>16],
["name" => "Kenneth Omeruo", "team_id" =>16],
["name" => "Bryan Idowu", "team_id" =>16],
["name" => "Chidozie Awaziem", "team_id" =>16],
["name" => "Abdullahi Shehu", "team_id" =>16],
["name" => "Elderson Echiejile", "team_id" =>16],
["name" => "Tyronne Ebuehi", "team_id" =>16],
["name" => "Stephen Eze", "team_id" =>16],
["name" => "Mikel John Obi", "team_id" =>16],
["name" => "Ogenyi Onazi", "team_id" =>16],
["name" => "John Ogu", "team_id" =>16],
["name" => "Wilfred Ndidi", "team_id" =>16],
["name" => "Uche Agbo", "team_id" =>16],
["name" => "Oghenekaro Etebo", "team_id" =>16],
["name" => "Joel Obi", "team_id" =>16],
["name" => "Mikel Agu", "team_id" =>16],
["name" => "Odion Ighalo", "team_id" =>16],
["name" => "Ahmed Musa", "team_id" =>16],
["name" => "Victor Moses", "team_id" =>16],
["name" => "Alex Iwobi", "team_id" =>16],
["name" => "Kelechi Ihenacho", "team_id" =>16],
["name" => "Moses Simon", "team_id" =>16],
["name" => "Junior Lokosa", "team_id" =>16],
["name" => "Simeon Nwankwo", "team_id" =>16],
["name" => "José Calderón (Chorrillo FC)", "team_id" =>26],
["name" => "Jaime Penedo (Dinamo Bucharest)", "team_id" =>26],
["name" => "Alex Rodríguez (San Francisco FC)", "team_id" =>26],
["name" => "Azmahar Ariano (Patriotas FC)", "team_id" =>26],
["name" => "Felipe Baloy (CSD Municipal)", "team_id" =>26],
["name" => "Harold Cummings (San José Earthquakes)", "team_id" =>26],
["name" => "Eric Davis (DAC Dunajska Streda)", "team_id" =>26],
["name" => "Fidel Escobar (New York Red Bulls)", "team_id" =>26],
["name" => "Adolfo Machado (Houston Dynamo)", "team_id" =>26],
["name" => "Michael Murillo (New York Red Bulls)", "team_id" =>26],
["name" => "Luis Ovalle (CD Olimpia)", "team_id" =>26],
["name" => "Francisco Palacios (San Francisco FC)", "team_id" =>26],
["name" => "Richard Peralta (Alianza)", "team_id" =>26],
["name" => "Román Torres (Seattle Sounders SC)", "team_id" =>26],
["name" => "Ricardo Ávila (KAA Gent)", "team_id" =>26],
["name" => "Edgar Barcenas (Cafetaleros de Tapachula)", "team_id" =>26],
["name" => "Ricardo Buitrago (CSD Municipal)", "team_id" =>26],
["name" => "Miguel Camargo (Universidad San Martín de Porres)", "team_id" =>26],
["name" => "Adalberto Carrasquilla (Tauro FC)", "team_id" =>26],
["name" => "Armando Cooper (Club Universidad de Chile)", "team_id" =>26],
["name" => "Aníbal Godoy (San José Earthquakes)", "team_id" =>26],
["name" => "Gabriel Gómez (Bucaramanga)", "team_id" =>26],
["name" => "José González (Unión Comercio)", "team_id" =>26],
["name" => "Cristian Martínez (Columbus Crew)", "team_id" =>26],
["name" => "Valentín Pimentel (Plaza Amador)", "team_id" =>26],
["name" => "Alberto Quintero (Universitario de Lima)", "team_id" =>26],
["name" => "José Luis Rodríguez (KAA Gent).", "team_id" =>26],
["name" => "Abdiel Arroyo (LD Alajuelense)", "team_id" =>26],
["name" => "Rolando Blackburn (Chorrillo FC)", "team_id" =>26],
["name" => "Ismael Díaz (Deportivo La Coruña)", "team_id" =>26],
["name" => "José Fajardo (CA Independiente)", "team_id" =>26],
["name" => "Roberto Nurse (Mineros Zacatecas)", "team_id" =>26],
["name" => "Blas Pérez (CSD Municipal)", "team_id" =>26],
["name" => "Luis Tejada (Sports Boys)", "team_id" =>26],
["name" => "Gabriel Torres (CD Huachipato)", "team_id" =>26],
["name" => "Pedro Gallese", "team_id" =>11],
["name" => "Carlos Cáceda", "team_id" =>11],
["name" => "José Carvallo", "team_id" =>11],
["name" => "Aldo Corzo", "team_id" =>11],
["name" => "Luis Advíncula", "team_id" =>11],
["name" => "Miguel Araujo", "team_id" =>11],
["name" => "Alberto Rodríguez", "team_id" =>11],
["name" => "Christian Ramos", "team_id" =>11],
["name" => "Anderson Santamaría", "team_id" =>11],
["name" => "Luis Abram", "team_id" =>11],
["name" => "Pedro Aquino", "team_id" =>11],
["name" => "Renato Tapia", "team_id" =>11],
["name" => "Miguel Trauco", "team_id" =>11],
["name" => "Nilson Loyola", "team_id" =>11],
["name" => "Yoshimar Yotún", "team_id" =>11],
["name" => "Sergio Peña", "team_id" =>11],
["name" => "Edison Flores", "team_id" =>11],
["name" => "Paolo Hurtado", "team_id" =>11],
["name" => "Wilder Cartagena", "team_id" =>11],
["name" => "Christian Cueva", "team_id" =>11],
["name" => "André Carrillo", "team_id" =>11],
["name" => "Andy Polo", "team_id" =>11],
["name" => "Jefferson Farfán", "team_id" =>11],
["name" => "Raúl Ruidíaz", "team_id" =>11],
["name" => "Bartosz Bialkowski (Ipswich Town)", "team_id" =>29],
["name" => "Lukasz Fabianski (Swansea City)", "team_id" =>29],
["name" => "Lukasz Skorupski (Roma)", "team_id" =>29],
["name" => "Wojciech Szczesny (Juventus)", "team_id" =>29],
["name" => "Jan Bednarek (Southampton)", "team_id" =>29],
["name" => "Bartosz Bereszynski (Sampdoria)", "team_id" =>29],
["name" => "Thiago Cionek (SPAL)", "team_id" =>29],
["name" => "Kamil Glik (Mónaco)", "team_id" =>29],
["name" => "Marcin Kaminski (Stuttgart)", "team_id" =>29],
["name" => "Tomasz Kedziora (Dinamo Kiev)", "team_id" =>29],
["name" => "Lukasz Piszczek (Borussia Dortmund)", "team_id" =>29],
["name" => "Artur Jedrzejczyk (Legia Varsovia)", "team_id" =>29],
["name" => "Michal Pazdan (Legia Varsovia)", "team_id" =>29],
["name" => "Jakub Blaszczykowski (Wolfsburg)", "team_id" =>29],
["name" => "Pawel Dawidowicz (Palermo)", "team_id" =>29],
["name" => "Przemyslaw Frankowski (Jagiellonia Bialystok)", "team_id" =>29],
["name" => "Jacek Góralski (Ludogorets Razgrad)", "team_id" =>29],
["name" => "Kamil Grosicki (Hull City)", "team_id" =>29],
["name" => "Grzegorz Krychowiak (West Brom)", "team_id" =>29],
["name" => "Rafal Kurzawa (Górnik Zabrze)", "team_id" =>29],
["name" => "Karol Linetty (Sampdoria)", "team_id" =>29],
["name" => "Krzysztof Maczynski (Legia Varsovia)", "team_id" =>29],
["name" => "Slawomir Peszko (Lechia Gdansk)", "team_id" =>29],
["name" => "Maciej Rybus (Lokomotiv Moscú)", "team_id" =>29],
["name" => "Sebastian Szymanski (Legia Varsovia)", "team_id" =>29],
["name" => "Piotr Zielinski (Nápoles)", "team_id" =>29],
["name" => "Szymon Zurkowski (Górnik Zabrze)", "team_id" =>29],
["name" => "Dawid Kownacki (Sampdoria)", "team_id" =>29],
["name" => "Robert Lewandowski (Bayern Múnich)", "team_id" =>29],
["name" => "Arkadiusz Milik (Nápoles)", "team_id" =>29],
["name" => "Lukasz Teodorczyk (Anderlecht)", "team_id" =>29],
["name" => "Kamil Wilczek (Brondby)", "team_id" =>29],
["name" => "Anthony Lopes (Lyon)", "team_id" =>5],
["name" => "Beto (Goztepe)", "team_id" =>5],
["name" => "Rui Patrício (Sporting)", "team_id" =>5],
["name" => "Bruno Alves (Rangers)", "team_id" =>5],
["name" => "Cédric Soares (Southampton)", "team_id" =>5],
["name" => "José Fonte (Dalian Yifang)", "team_id" =>5],
["name" => "Mário Rui (Nápoles)", "team_id" =>5],
["name" => "Pepe (Besiktas)", "team_id" =>5],
["name" => "Raphael Guerreiro (Dortmund)", "team_id" =>5],
["name" => "Ricardo Pereira (FC Porto)", "team_id" =>5],
["name" => "Rúben Dias (Benfica)", "team_id" =>5],
["name" => "Adrien Silva (Leicester)", "team_id" =>5],
["name" => "Bruno Fernandes (Sporting)", "team_id" =>5],
["name" => "João Mário (West Ham)", "team_id" =>5],
["name" => "João Moutinho (Mónaco)", "team_id" =>5],
["name" => "Manuel Fernandes (Lokomotiv)", "team_id" =>5],
["name" => "William Carvalho (Sporting)", "team_id" =>5],
["name" => "André Silva (Milán)", "team_id" =>5],
["name" => "Bernardo Silva (Manchester City)", "team_id" =>5],
["name" => "Cristiano Ronaldo (Real Madrid)", "team_id" =>5],
["name" => "Gelson Martins (Sporting)", "team_id" =>5],
["name" => "Gonçalo Guedes (Valencia)", "team_id" =>5],
["name" => "Ricardo Quaresma (Besiktas)", "team_id" =>5],
["name" => "Igor Akinfeev (CSKA Moscú)", "team_id" =>1],
["name" => "Vladimir Gabulov (Club Brugge)", "team_id" =>1],
["name" => "Soslan Dzhanaev (Rubin Kazan)", "team_id" =>1],
["name" => "Andrey Lunyov (FC Zenit)", "team_id" =>1],
["name" => "Vladimir Granat (FC Rubin)", "team_id" =>1],
["name" => "Ruslan Kambolov (FC Rubin)", "team_id" =>1],
["name" => "Fedor Kudryashov (FC Rubin)", "team_id" =>1],
["name" => "Ilya Kutepov (Spartak Moscú)", "team_id" =>1],
["name" => "Roman Neustadter (Fenerbahçe)", "team_id" =>1],
["name" => "Konstantin Rausch (Dinamo Moscú)", "team_id" =>1],
["name" => "Andrey Semenov (Akhmat Grozny)", "team_id" =>1],
["name" => "Igor Smolnikov (FC Zenit)", "team_id" =>1],
["name" => "Mario Fernandes (CSKA Moscú)", "team_id" =>1],
["name" => "Yuri Gazinskiy (Krasnodar)", "team_id" =>1],
["name" => "Aleksandr Golovin (CSKA Moscú)", "team_id" =>1],
["name" => "Alan Dzagoev (CSKA Moscú)", "team_id" =>1],
["name" => "Aleksandr Erokhin (Zenit)", "team_id" =>1],
["name" => "Yuri Zhirkov (Zenit)", "team_id" =>1],
["name" => "Daler Kuzyaev (Zenit)", "team_id" =>1],
["name" => "Roman Zobnin (Spartak Moscú)", "team_id" =>1],
["name" => "Aleksandr Samedov (Spartak Moscú)", "team_id" =>1],
["name" => "Anton Miranchuk (Lokomotiv Moscú)", "team_id" =>1],
["name" => "Aleksandr Tashaev (Dynamo Moscú)", "team_id" =>1],
["name" => "Denis Cheryshev (Villarreal)", "team_id" =>1],
["name" => "Artem Dzyuba (Arsenal Tula)", "team_id" =>1],
["name" => "Aleksey Miranchuk (Lokomotiv Moscow)", "team_id" =>1],
["name" => "Fedor Smolov (Krasnodar)", "team_id" =>1],
["name" => "Fedor Chalov (CSKA Moscow)", "team_id" =>1],
["name" => "Martello Guilherme (Lokomotiv Moscú)", "team_id" =>1],
["name" => "Vladislav Ignatyev (Lokomotiv Moscú)", "team_id" =>1],
["name" => "Dmitri Kombarov (Spartak Moscú)", "team_id" =>1],
["name" => "Denis Glushakov (Spartak Moscú)", "team_id" =>1],
["name" => "Anton Shvets (Akhmat Grozny)", "team_id" =>1],
["name" => "Anton Zabolotny (Zenit)", "team_id" =>1],
["name" => "Dmitry Poloz (Zenit)", "team_id" =>1],
["name" => "Abdoulaye Diallo (Stade Rennes)", "team_id" =>30],
["name" => "Alfred Gomis (Spal)", "team_id" =>30],
["name" => "Khadim Ndiaye (Horoya Athletic)", "team_id" =>30],
["name" => "Kalidou Koulibaly (Nápoles)", "team_id" =>30],
["name" => "Kara Mbodji (Anderlecht)", "team_id" =>30],
["name" => "Lamine Gassama (Alanyaspor)", "team_id" =>30],
["name" => "Moussa Wague (Kas Eupen)", "team_id" =>30],
["name" => "Youssouf Sabaly (Girondins)", "team_id" =>30],
["name" => "Saliou Ciss (Valenciennes)", "team_id" =>30],
["name" => "Salif Sane (Hannover 96)", "team_id" =>30],
["name" => "Pape Alioune Ndiaye (Stoke City)", "team_id" =>30],
["name" => "Cheikh Tidiane Ndoye (Birmingham)", "team_id" =>30],
["name" => "Cheikhou Kouyate (West Ham)", "team_id" =>30],
["name" => "Alfred Ndiaye (Wolverhampton)", "team_id" =>30],
["name" => "Idrissa Gana Gueyé (Everton)", "team_id" =>30],
["name" => "Mbaye Hamady Niang (Torino)", "team_id" =>30],
["name" => "Diafra Sakho (Stade Rennes)", "team_id" =>30],
["name" => "Moussa Konaté (Amiens)", "team_id" =>30],
["name" => "Ismaila Sarr (Stade Rennes)", "team_id" =>30],
["name" => "Keita Baldé (Mónaco)", "team_id" =>30],
["name" => "Mame Biram Diouf (Stoke City)", "team_id" =>30],
["name" => "Moussa Sow (Bursaspor)", "team_id" =>30],
["name" => "Sadio Mané (Liverpool)", "team_id" =>30],
["name" => "Robin Olsen (Copenhague)", "team_id" =>23],
["name" => "Karl-Johan Johnsson (Guingamp)", "team_id" =>23],
["name" => "Kristoffer Nordfeldt (Swansea).", "team_id" =>23],
["name" => "Mikael Lustig (Celtic)", "team_id" =>23],
["name" => "Victor Nilsson Lindelöf (Manchester United)", "team_id" =>23],
["name" => "Andreas Granqvist (Krasnodar)", "team_id" =>23],
["name" => "Martin Olsson (Swansea)", "team_id" =>23],
["name" => "Ludwig Augustinsson (Werder Bremen)", "team_id" =>23],
["name" => "Filip Helander (Bologna) ", "team_id" =>23],
["name" => "Emil Krafth (Bologna) ", "team_id" =>23],
["name" => "Pontus Jansson (Leeds)", "team_id" =>23],
["name" => "Victor Claesson (Krasnodar)", "team_id" =>23],
["name" => "Jimmy Durmaz (Toulouse)", "team_id" =>23],
["name" => "Emil Forsberg (Leipzig)", "team_id" =>23],
["name" => "Sebastian Larsson (Hull)", "team_id" =>23],
["name" => "Gustav Svensson (Seattle)", "team_id" =>23],
["name" => "Albin Ekdal (Hamburgo) ", "team_id" =>23],
["name" => "Oscar Hiljemark (Génova)", "team_id" =>23],
["name" => "Marcus Rohdén (Crotone)", "team_id" =>23],
["name" => "Marcus Berg (Al Ain)", "team_id" =>23],
["name" => "John Guidetti (Alavés)", "team_id" =>23],
["name" => "Isaac Kiese Thelin (Waasland-Beveren)", "team_id" =>23],
["name" => "Ola Toivonen (Toulouse)", "team_id" =>23],
["name" => "Aymen Mathlouthi", "team_id" =>27],
["name" => "Mouez Hassen", "team_id" =>27],
["name" => "Farouk Ben Mustapha", "team_id" =>27],
["name" => "Moez Ben Chrifia", "team_id" =>27],
["name" => "Syam Ben Youssef", "team_id" =>27],
["name" => "Yohan Benalouane", "team_id" =>27],
["name" => "Yassine Meriah", "team_id" =>27],
["name" => "Bilel Mohnsni", "team_id" =>27],
["name" => "Rami Bedoui", "team_id" =>27],
["name" => "Hamdi Nagguez", "team_id" =>27],
["name" => "Ali Maaloul", "team_id" =>27],
["name" => "Khalil Chemmam", "team_id" =>27],
["name" => "Oussema Haddadi", "team_id" =>27],
["name" => "Dylan Bronn", "team_id" =>27],
["name" => "Ellyes Skhiri", "team_id" =>27],
["name" => "Ferjani Sassi", "team_id" =>27],
["name" => "Karim Laribi", "team_id" =>27],
["name" => "Ahmed Khalil", "team_id" =>27],
["name" => "Mohamed Amine Ben Amor", "team_id" =>27],
["name" => "Ghailene Chaalali", "team_id" =>27],
["name" => "Mohamed Larbi", "team_id" =>27],
["name" => "Anice Badri", "team_id" =>27],
["name" => "Saif-Eddine Khaoui", "team_id" =>27],
["name" => "Saber Khalifa", "team_id" =>27],
["name" => "Naim Sliti", "team_id" =>27],
["name" => "Fakhreddine Ben Youssef", "team_id" =>27],
["name" => "Wahbi Khazri", "team_id" =>27],
["name" => "Bassem Srarfi", "team_id" =>27],
["name" => "Ahmed Akaichi", "team_id" =>27],
["name" => "Fernando Muslera (Galatasaray)", "team_id" =>4],
["name" => "Martín Silva (Vasco de Gama)", "team_id" =>4],
["name" => "Martín Campana (Independiente)", "team_id" =>4],
["name" => "Diego Godín (Atlético de Madrid)", "team_id" =>4],
["name" => "Sebastián Coates (Sporting de Portugal)", "team_id" =>4],
["name" => "José María Giménez (Atlético de Madrid)", "team_id" =>4],
["name" => "Maximiliano Pereira (Oporto)", "team_id" =>4],
["name" => "Gastón Silva (Independiente)", "team_id" =>4],
["name" => "Martín Cáceres (Lazio)", "team_id" =>4],
["name" => "Guillermo Varela (Peñarol)", "team_id" =>4],
["name" => "Nahitan Nández (Boca Juniors)", "team_id" =>4],
["name" => "Lucas Torreira (Sampdoria)", "team_id" =>4],
["name" => "Matías Vecino (Inter de Milán)", "team_id" =>4],
["name" => "Federico Valverde (Deportivo de la Coruña)", "team_id" =>4],
["name" => "Rodrigo Betancur (Juventus)", "team_id" =>4],
["name" => "Carlos Sánchez (Monterrey)", "team_id" =>4],
["name" => "Gastón Ramírez (Sampdoria)", "team_id" =>4],
["name" => "Nicolás Lodeiro (Seattle Sounders)", "team_id" =>4],
["name" => "Jonathan Urretaviscaya (Pachuca)", "team_id" =>4],
["name" => "Giorgian de Arrascaeta (Cruzeiro)", "team_id" =>4],
["name" => "Diego Laxalt (Genoa)", "team_id" =>4],
["name" => "Cristian Rodríguez (Peñarol)", "team_id" =>4],
["name" => "Christian Stuani (Girona)", "team_id" =>4],
["name" => "Edinson Cavani (PSG)", "team_id" =>4],
["name" => "Maximiliano Gómez (Celta)", "team_id" =>4],
["name" => "Luis Suárez (Barcelona)", "team_id" =>4],
["name" => "David De Gea (Manchester United)", "team_id" =>6],
["name" => "Pepe Reina (Nápoles)", "team_id" =>6],
["name" => "Kepa Arrizabalaga (Athletic Club)", "team_id" =>6],
["name" => "Dani Carvajal (Real Madrid)", "team_id" =>6],
["name" => "Álvaro Odriozola (Real Sociedad)", "team_id" =>6],
["name" => "Gerard Piqué (FC Barcelona)", "team_id" =>6],
["name" => "Sergio Ramos (Real Madrid)", "team_id" =>6],
["name" => "Nacho Fernández (Real Madrid)", "team_id" =>6],
["name" => "César Azpilicueta (Chelsea)", "team_id" =>6],
["name" => "Jordi Alba (FC Barcelona)", "team_id" =>6],
["name" => "Nacho Monreal (Arsenal)", "team_id" =>6],
["name" => "Sergio Busquets (FC Barcelona)", "team_id" =>6],
["name" => "Saúl Ñíguez (Atlético de Madrid)", "team_id" =>6],
["name" => "Koke Resurrección (Atlético de Madrid)", "team_id" =>6],
["name" => "Thiago Alcántara (Bayern Múnich)", "team_id" =>6],
["name" => "Andrés Iniesta (FC Barcelona)", "team_id" =>6],
["name" => "David Silva (Manchester City)", "team_id" =>6],
["name" => "Isco Alarcón (Real Madrid)", "team_id" =>6],
["name" => "Marco Asensio (Real Madrid)", "team_id" =>6],
["name" => "Lucas Vázquez (Real Madrid)", "team_id" =>6],
["name" => "Iago Aspas (Celta de Vigo)", "team_id" =>6],
["name" => "Rodrigo Moreno (Valencia CF)", "team_id" =>6],
["name" => "Diego Costa (Atlético de Madrid)", "team_id" =>6],
["name" => "Koen Casteels (Wolfsbourg)", "team_id" =>25],
["name" => "Thibaut Courtois (Chelsea)", "team_id" =>25],
["name" => "Simon Mignolet (Liverpool)", "team_id" =>25],
["name" => "Matz Sels (Anderlecht)", "team_id" =>25],
["name" => "Toby Alberweild (Tottenham)", "team_id" =>25],
["name" => "Dedryck Boyata (Celtic)", "team_id" =>25],
["name" => "Laurent Ciman (Los Angeles FC)", "team_id" =>25],
["name" => "Vincent Kompany (Manchester City)", "team_id" =>25],
["name" => "Thomas Meunier (PSG)", "team_id" =>25],
["name" => "Thomas Vermaelen (Barcelona)", "team_id" =>25],
["name" => "Christian Kabasele (Warford)", "team_id" =>25],
["name" => "Jordan Lukaku (Lazio)", "team_id" =>25],
["name" => "Jan Vertonghen (Tottenham)", "team_id" =>25],
["name" => "Yannick Carrasco (Dalian Yfang)", "team_id" =>25],
["name" => "Nacer Chadli (West Bromwich Albion)", "team_id" =>25],
["name" => "Kevin De Bruyne (Chelsea)", "team_id" =>25],
["name" => "Mousa Dembele (Tottenham)", "team_id" =>25],
["name" => "Dries Mertens (Nápoles)", "team_id" =>25],
["name" => "Youri Tielemans (Mónaco)", "team_id" =>25],
["name" => "Axel Witsel (Tianjin Quanjian)", "team_id" =>25],
["name" => "Leander Dendoncker (Anderlecht)", "team_id" =>25],
["name" => "Marouane Fellaini (Manchester United)", "team_id" =>25],
["name" => "Thorgan Hazard (Borussia Monchengladbach)", "team_id" =>25],
["name" => "Adnan Januzaj (Real Sociedad)", "team_id" =>25],
["name" => "Michy Batshuayi (Borussia Dortmund)", "team_id" =>25],
["name" => "Christian Benteke (Crystal Palace)", "team_id" =>25],
["name" => "Romelu Lukaku (Manchester United)", "team_id" =>25],
["name" => "Eden Hazard (Chelsea) ", "team_id" =>25],
        ];

         foreach ($players as $player) {
            DB::table('players')->insert([
                'name' => $player['name'],
                'team_id' => $player['team_id'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ]);
        }
    }
}
