<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class PlayersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $players = [
                        ['name' => 'Manuel Neuer', 'team_id' => 8],
            ['name' => 'Bernd Leno', 'team_id' => 8],
            ['name' => 'Marc-André ter Stegen', 'team_id' => 8],
            ['name' => 'Jérôme Boateng', 'team_id' => 8],
            ['name' => 'Mats Hummels', 'team_id' => 8],
            ['name' => 'Jonas Hector', 'team_id' => 8],
            ['name' => 'Benedikt Höwedes', 'team_id' => 8],
            ['name' => 'Antonio Rüdiger', 'team_id' => 8],
            ['name' => 'Emre Can', 'team_id' => 8],
            ['name' => 'Shkodran Mustafi', 'team_id' => 8],
            ['name' => 'Mario Götze', 'team_id' => 8],
            ['name' => 'Joshua Kimmich', 'team_id' => 8],
            ['name' => 'Toni Kroos', 'team_id' => 8],
            ['name' => 'Sami Khedira', 'team_id' => 8],
            ['name' => 'Bastian Schweinsteiger', 'team_id' => 8],
            ['name' => 'Julian Weigl', 'team_id' => 8],
            ['name' => 'Leroy Sané', 'team_id' => 8],
            ['name' => 'André Schürrle', 'team_id' => 8],
            ['name' => 'Julian Draxler', 'team_id' => 8],
            ['name' => 'Mesut Özil', 'team_id' => 8],
            ['name' => 'Mario Gómez', 'team_id' => 8],
            ['name' => 'Thomas Müller', 'team_id' => 8],
            ['name' => 'Lukas Podolski', 'team_id' => 8],
            ['name' => 'Matúš Kozáčik', 'team_id' => 18],
            ['name' => 'Ján Mucha', 'team_id' => 18],
            ['name' => 'Ján Novota', 'team_id' => 18],
            ['name' => 'Peter Pekarík', 'team_id' => 18],
            ['name' => 'Milan Škriniar', 'team_id' => 18],
            ['name' => 'Martin Škrtel', 'team_id' => 18],
            ['name' => 'Norbert Gyömbér', 'team_id' => 18],
            ['name' => 'Ján Ďurica', 'team_id' => 18],
            ['name' => 'Kornel Saláta', 'team_id' => 18],
            ['name' => 'Tomáš Hubočan', 'team_id' => 18],
            ['name' => 'Dušan Švento', 'team_id' => 18],
            ['name' => 'Marek Hamšík', 'team_id' => 18],
            ['name' => 'Juraj Kucka', 'team_id' => 18],
            ['name' => 'Miroslav Stoch', 'team_id' => 18],
            ['name' => 'Vladimír Weiss', 'team_id' => 18],
            ['name' => 'Róbert Mak', 'team_id' => 18],
            ['name' => 'Patrik Hrošovský', 'team_id' => 18],
            ['name' => 'Ján Greguš', 'team_id' => 18],
            ['name' => 'Viktor Pečovský', 'team_id' => 18],
            ['name' => 'Ondrej Duda', 'team_id' => 18],
            ['name' => 'Michal Ďuriš', 'team_id' => 18],
            ['name' => 'Adam Nemec', 'team_id' => 18],
            ['name' => 'Stanislav Šesták', 'team_id' => 18],
            ['name' => 'Iker Casillas', 'team_id' => 19],
            ['name' => 'David de Gea', 'team_id' => 19],
            ['name' => 'Sergio Rico', 'team_id' => 19],
            ['name' => 'Juanfran Torres', 'team_id' => 19],
            ['name' => 'Héctor Bellerín', 'team_id' => 19],
            ['name' => 'Sergio Ramos', 'team_id' => 19],
            ['name' => 'Gerard Piqué', 'team_id' => 19],
            ['name' => 'Marc Bartra', 'team_id' => 19],
            ['name' => 'Mikel San José', 'team_id' => 19],
            ['name' => 'Jordi Alba', 'team_id' => 19],
            ['name' => 'César Azpilicueta', 'team_id' => 19],
            ['name' => 'Sergio Busquets', 'team_id' => 19],
            ['name' => 'Bruno Soriano', 'team_id' => 19],
            ['name' => 'Andrés Iniesta', 'team_id' => 19],
            ['name' => 'Cesc Fábregas', 'team_id' => 19],
            ['name' => 'David Silva', 'team_id' => 19],
            ['name' => 'Thiago Alcántara', 'team_id' => 19],
            ['name' => 'Koke', 'team_id' => 19],
            ['name' => 'Álvaro Morata', 'team_id' => 19],
            ['name' => 'Aritz Aduriz', 'team_id' => 19],
            ['name' => 'Pedro Rodríguez', 'team_id' => 19],
            ['name' => 'Nolito', 'team_id' => 19],
            ['name' => 'Lucas Vázquez', 'team_id' => 19],
            ['name' => 'Hugo Lloris', 'team_id' => 7],
            ['name' => 'Steve Mandanda', 'team_id' => 7],
            ['name' => 'Benoït Costil', 'team_id' => 7],
            ['name' => 'Raphaël Varane', 'team_id' => 7],
            ['name' => 'Laurent Koscielny', 'team_id' => 7],
            ['name' => 'Eliaquim Mangala', 'team_id' => 7],
            ['name' => 'Jérémy Mathieu', 'team_id' => 7],
            ['name' => 'Bacary Sagna', 'team_id' => 7],
            ['name' => 'Christophe Jallet', 'team_id' => 7],
            ['name' => 'Patrice Evra', 'team_id' => 7],
            ['name' => 'Lucas Digne', 'team_id' => 7],
            ['name' => 'Lassana Diarra', 'team_id' => 7],
            ['name' => 'N’Golo Kanté', 'team_id' => 7],
            ['name' => 'Paul Pogba', 'team_id' => 7],
            ['name' => 'Yohan Cabaye', 'team_id' => 7],
            ['name' => 'Blaise Matuidi', 'team_id' => 7],
            ['name' => 'Moussa Sissoko', 'team_id' => 7],
            ['name' => 'Dimitri Payet', 'team_id' => 7],
            ['name' => 'Kingsley Coman', 'team_id' => 7],
            ['name' => 'Anthony Martial', 'team_id' => 7],
            ['name' => 'Antoine Griezmann', 'team_id' => 7],
            ['name' => 'Olivier Giroud', 'team_id' => 7],
            ['name' => 'André-Pierre Gignac', 'team_id' => 7],
            ['name' => 'Wayne Hennessey', 'team_id' => 24],
            ['name' => 'Daniel Ward', 'team_id' => 24],
            ['name' => 'Owain Fon Williams', 'team_id' => 24],
            ['name' => 'Ben Davies', 'team_id' => 24],
            ['name' => 'Neil Taylor', 'team_id' => 24],
            ['name' => 'Chris Gunter', 'team_id' => 24],
            ['name' => 'Ashley Williams', 'team_id' => 24],
            ['name' => 'James Chester', 'team_id' => 24],
            ['name' => 'Ashley Richards', 'team_id' => 24],
            ['name' => 'James Collins', 'team_id' => 24],
            ['name' => 'Aaron Ramsey', 'team_id' => 24],
            ['name' => 'Joe Ledley', 'team_id' => 24],
            ['name' => 'David Vaughan', 'team_id' => 24],
            ['name' => 'Joe Allen', 'team_id' => 24],
            ['name' => 'Jonathan Williams', 'team_id' => 24],
            ['name' => 'George Williams', 'team_id' => 24],
            ['name' => 'Andy King', 'team_id' => 24],
            ['name' => 'David Edwards', 'team_id' => 24],
            ['name' => 'Gareth Bale', 'team_id' => 24],
            ['name' => 'Hal Robson-Kanu', 'team_id' => 24],
            ['name' => 'Sam Vokes', 'team_id' => 24],
            ['name' => 'Simon Church', 'team_id' => 24],
            ['name' => 'David Cotterill', 'team_id' => 24],
            ['name' => 'Gábor Király', 'team_id' => 9],
            ['name' => 'Dénes Dibusz', 'team_id' => 9],
            ['name' => 'Péter Gulácsi', 'team_id' => 9],
            ['name' => 'Attila Fiola', 'team_id' => 9],
            ['name' => 'Barnabás Bese', 'team_id' => 9],
            ['name' => 'Richárd Guzmics', 'team_id' => 9],
            ['name' => 'Roland Juhász', 'team_id' => 9],
            ['name' => 'Ádám Lang', 'team_id' => 9],
            ['name' => 'Tamás Kádár', 'team_id' => 9],
            ['name' => 'Mihály Korhut', 'team_id' => 9],
            ['name' => 'Balázs Dzsudzsák', 'team_id' => 9],
            ['name' => 'Ákos Elek', 'team_id' => 9],
            ['name' => 'Zoltán Gera', 'team_id' => 9],
            ['name' => 'Ádám Nagy', 'team_id' => 9],
            ['name' => 'László Kleinheisler', 'team_id' => 9],
            ['name' => 'Zoltán Stieber', 'team_id' => 9],
            ['name' => 'Gergo Lovrensics', 'team_id' => 9],
            ['name' => 'Adam Pinter', 'team_id' => 9],
            ['name' => 'Ádám Szalai', 'team_id' => 9],
            ['name' => 'Krisztián Németh', 'team_id' => 9],
            ['name' => 'Nemanja Nikolic', 'team_id' => 9],
            ['name' => 'Tamás Priskin', 'team_id' => 9],
            ['name' => 'Dániel Böde', 'team_id' => 9],
            ['name' => 'Joe Hart', 'team_id' => 6],
            ['name' => 'Fraser Forster', 'team_id' => 6],
            ['name' => 'Tom Heaton', 'team_id' => 6],
            ['name' => 'Ryan Bertrand', 'team_id' => 6],
            ['name' => 'Gary Cahill', 'team_id' => 6],
            ['name' => 'Nathaniel Clyne', 'team_id' => 6],
            ['name' => 'Kyle Walker', 'team_id' => 6],
            ['name' => 'Danny Rose', 'team_id' => 6],
            ['name' => 'Chris Smalling', 'team_id' => 6],
            ['name' => 'John Stones', 'team_id' => 6],
            ['name' => 'Dele Alli', 'team_id' => 6],
            ['name' => 'Ross Barkley', 'team_id' => 6],
            ['name' => 'Eric Dier', 'team_id' => 6],
            ['name' => 'Jordan Henderson', 'team_id' => 6],
            ['name' => 'Adam Lallana', 'team_id' => 6],
            ['name' => 'James Milner', 'team_id' => 6],
            ['name' => 'Raheem Sterling', 'team_id' => 6],
            ['name' => 'Jack Wilshere', 'team_id' => 6],
            ['name' => 'Harry Kane', 'team_id' => 6],
            ['name' => 'Wayne Rooney', 'team_id' => 6],
            ['name' => 'Daniel Sturridge', 'team_id' => 6],
            ['name' => 'Marcus Rashford', 'team_id' => 6],
            ['name' => 'Jamie Vardy', 'team_id' => 6],
            ['name' => 'Roy Carroll', 'team_id' => 12],
            ['name' => 'Michael McGovern', 'team_id' => 12],
            ['name' => 'Alan Mannus', 'team_id' => 12],
            ['name' => 'Aaron Hughes', 'team_id' => 12],
            ['name' => 'Chris Baird', 'team_id' => 12],
            ['name' => 'Gareth McAuley', 'team_id' => 12],
            ['name' => 'Jonny Evans', 'team_id' => 12],
            ['name' => 'Craig Cathcart', 'team_id' => 12],
            ['name' => 'Paddy McNair', 'team_id' => 12],
            ['name' => 'Conor McLaughlin', 'team_id' => 12],
            ['name' => 'Lee Hodson', 'team_id' => 12],
            ['name' => 'Luke McCullough', 'team_id' => 12],
            ['name' => 'Steven Davis', 'team_id' => 12],
            ['name' => 'Oliver Norwood', 'team_id' => 12],
            ['name' => 'Corry Evans', 'team_id' => 12],
            ['name' => 'Shane Ferguson', 'team_id' => 12],
            ['name' => 'Stuart Dallas', 'team_id' => 12],
            ['name' => 'Niall McGinn', 'team_id' => 12],
            ['name' => 'Jamie Ward', 'team_id' => 12],
            ['name' => 'Kyle Lafferty', 'team_id' => 12],
            ['name' => 'Josh Magennis', 'team_id' => 12],
            ['name' => 'Will Grigg', 'team_id' => 12],
            ['name' => 'Conor Washington', 'team_id' => 12],
            ['name' => 'Hannes Halldórsson', 'team_id' => 10],
            ['name' => 'Ögmundur Kristinsson', 'team_id' => 10],
            ['name' => 'Ingvar Jónsson', 'team_id' => 10],
            ['name' => 'Ari Skúlason', 'team_id' => 10],
            ['name' => 'Hordur Magnússon', 'team_id' => 10],
            ['name' => 'Hjörtur Hermannsson', 'team_id' => 10],
            ['name' => 'Ragnar Sigurdsson', 'team_id' => 10],
            ['name' => 'Kári Árnason', 'team_id' => 10],
            ['name' => 'Sverrir Ingi Ingason', 'team_id' => 10],
            ['name' => 'Birkir Sævarsson', 'team_id' => 10],
            ['name' => 'Haukur Heidar Hauksson', 'team_id' => 10],
            ['name' => 'Emil Hallfredsson', 'team_id' => 10],
            ['name' => 'Gylfi Sigurdsson', 'team_id' => 10],
            ['name' => 'Aron Gunnarsson', 'team_id' => 10],
            ['name' => 'Theódór Elmar Bjarnason', 'team_id' => 10],
            ['name' => 'Arnór Ingvi Traustason', 'team_id' => 10],
            ['name' => 'Birkir Bjarnason', 'team_id' => 10],
            ['name' => 'Johann Gudmundsson', 'team_id' => 10],
            ['name' => 'Eidur Gudjohnsen', 'team_id' => 10],
            ['name' => 'Rúnar Már Sigurjónsson', 'team_id' => 10],
            ['name' => 'Kolbeinn Sigthórsson', 'team_id' => 10],
            ['name' => 'Alfred Finnbogason', 'team_id' => 10],
            ['name' => 'Jón Dadi Bödvarsson', 'team_id' => 10],
            ['name' => 'Artur Boruc', 'team_id' => 13],
            ['name' => 'Łukasz Fabiański', 'team_id' => 13],
            ['name' => 'Wojciech Szczęsny', 'team_id' => 13],
            ['name' => 'Kamil Glik', 'team_id' => 13],
            ['name' => 'Michał Pazdan', 'team_id' => 13],
            ['name' => 'Bartosz Salamon', 'team_id' => 13],
            ['name' => 'Thiago Cionek', 'team_id' => 13],
            ['name' => 'Łukasz Piszczek', 'team_id' => 13],
            ['name' => 'Artur Jędrzejczyk', 'team_id' => 13],
            ['name' => 'Jakub Wawrzyniak', 'team_id' => 13],
            ['name' => 'Tomasz Jodłowiec', 'team_id' => 13],
            ['name' => 'Grzegorz Krychowiak', 'team_id' => 13],
            ['name' => 'Krzysztof Mączyński', 'team_id' => 13],
            ['name' => 'Piotr Zieliński', 'team_id' => 13],
            ['name' => 'Karol Linetty', 'team_id' => 13],
            ['name' => 'Filip Starzyński', 'team_id' => 13],
            ['name' => 'Jakub Błaszczykowski', 'team_id' => 13],
            ['name' => 'Kamil Grosicki', 'team_id' => 13],
            ['name' => 'Sławomir Peszko', 'team_id' => 13],
            ['name' => 'Bartosz Kapustka', 'team_id' => 13],
            ['name' => 'Robert Lewandowski', 'team_id' => 13],
            ['name' => 'Arkadiusz Milik', 'team_id' => 13],
            ['name' => 'Mariusz Stępiński', 'team_id' => 13],
            ['name' => 'Anthony Lopes', 'team_id' => 14],
            ['name' => 'Eduardo', 'team_id' => 14],
            ['name' => 'Rui Patricio', 'team_id' => 14],
            ['name' => 'Bruno Alves', 'team_id' => 14],
            ['name' => 'Cédric', 'team_id' => 14],
            ['name' => 'Eliseu', 'team_id' => 14],
            ['name' => 'José Fonte', 'team_id' => 14],
            ['name' => 'Pepe', 'team_id' => 14],
            ['name' => 'Raphael Guerreiro', 'team_id' => 14],
            ['name' => 'Ricardo Carvalho', 'team_id' => 14],
            ['name' => 'Vieirinha', 'team_id' => 14],
            ['name' => 'Adrien Silva', 'team_id' => 14],
            ['name' => 'André Gomes', 'team_id' => 14],
            ['name' => 'Danilo', 'team_id' => 14],
            ['name' => 'Joao Mario', 'team_id' => 14],
            ['name' => 'Joao Moutinho', 'team_id' => 14],
            ['name' => 'Rafa', 'team_id' => 14],
            ['name' => 'Renato Sanches', 'team_id' => 14],
            ['name' => 'William Carvalho', 'team_id' => 14],
            ['name' => 'Cristiano Ronaldo', 'team_id' => 14],
            ['name' => 'Éder', 'team_id' => 14],
            ['name' => 'Nani', 'team_id' => 14],
            ['name' => 'Ricardo Quaresma', 'team_id' => 14],
            ['name' => 'Igor Akinfeev', 'team_id' => 17],
            ['name' => 'Yuri Lodygin', 'team_id' => 17],
            ['name' => 'Guilherme', 'team_id' => 17],
            ['name' => 'Aleksei Berezutski', 'team_id' => 17],
            ['name' => 'Vasili Berezutski', 'team_id' => 17],
            ['name' => 'Sergei Ignashevich', 'team_id' => 17],
            ['name' => 'Dmitri Kombarov', 'team_id' => 17],
            ['name' => 'Roman Neustädter', 'team_id' => 17],
            ['name' => 'Georgi Schennikov', 'team_id' => 17],
            ['name' => 'Roman Shishkin', 'team_id' => 17],
            ['name' => 'Igor Smolnikov', 'team_id' => 17],
            ['name' => 'Igor Denisov', 'team_id' => 17],
            ['name' => 'Dmitri Torbinski', 'team_id' => 17],
            ['name' => 'Aleksandr Golovin', 'team_id' => 17],
            ['name' => 'Denis Glushakov', 'team_id' => 17],
            ['name' => 'Oleg Ivanov', 'team_id' => 17],
            ['name' => 'Pavel Mamaev', 'team_id' => 17],
            ['name' => 'Aleksandr Samedov', 'team_id' => 17],
            ['name' => 'Oleg Shatov', 'team_id' => 17],
            ['name' => 'Roman Shirokov', 'team_id' => 17],
            ['name' => 'Artem Dzyuba', 'team_id' => 17],
            ['name' => 'Aleksandr Kokorin', 'team_id' => 17],
            ['name' => 'Fedor Smolov', 'team_id' => 17],
            ['name' => 'Patrik Carlgren', 'team_id' => 20],
            ['name' => 'Andreas Isaksson', 'team_id' => 20],
            ['name' => 'Robin Olsen', 'team_id' => 20],
            ['name' => 'Ludwig Augustinsson', 'team_id' => 20],
            ['name' => 'Andreas Granqvist', 'team_id' => 20],
            ['name' => 'Pontus Jansson', 'team_id' => 20],
            ['name' => 'Erik Johannsson', 'team_id' => 20],
            ['name' => 'Mikael Lustig', 'team_id' => 20],
            ['name' => 'Victor Lindelöf', 'team_id' => 20],
            ['name' => 'Martin Olsson', 'team_id' => 20],
            ['name' => 'Jimmy Durmaz', 'team_id' => 20],
            ['name' => 'Albin Ekdal', 'team_id' => 20],
            ['name' => 'Emil Forsberg', 'team_id' => 20],
            ['name' => 'Oscar Hiljemark', 'team_id' => 20],
            ['name' => 'Kim Källstrom', 'team_id' => 20],
            ['name' => 'Sebastian Larsson', 'team_id' => 20],
            ['name' => 'Oscar Lewicki', 'team_id' => 20],
            ['name' => 'Pontus Wernbloom', 'team_id' => 20],
            ['name' => 'Erkan Zengin', 'team_id' => 20],
            ['name' => 'Marcus Berg', 'team_id' => 20],
            ['name' => 'John Guidetti', 'team_id' => 20],
            ['name' => 'Zlatan Ibrahimovic', 'team_id' => 20],
            ['name' => 'Emir Kujovic', 'team_id' => 20],
            ['name' => 'Yann Sommer', 'team_id' => 21],
            ['name' => 'Roman Bürki', 'team_id' => 21],
            ['name' => 'Marwin Hitz', 'team_id' => 21],
            ['name' => 'Johan Djourou', 'team_id' => 21],
            ['name' => 'Steve von Bergen', 'team_id' => 21],
            ['name' => 'Fabian Schär', 'team_id' => 21],
            ['name' => 'Nico Elvedi', 'team_id' => 21],
            ['name' => 'Stephan Lichtsteiner', 'team_id' => 21],
            ['name' => 'Michael Lang', 'team_id' => 21],
            ['name' => 'Ricardo Rodríguez', 'team_id' => 21],
            ['name' => 'François Moubandje', 'team_id' => 21],
            ['name' => 'Valon Behrami', 'team_id' => 21],
            ['name' => 'Gelson Fernandes', 'team_id' => 21],
            ['name' => 'Denis Zakaria', 'team_id' => 21],
            ['name' => 'Granit Xhaka', 'team_id' => 21],
            ['name' => 'Blerim Dzemaili', 'team_id' => 21],
            ['name' => 'Fabian Frei', 'team_id' => 21],
            ['name' => 'Admir Mehmedi', 'team_id' => 21],
            ['name' => 'Xherdan Shaqiri', 'team_id' => 21],
            ['name' => 'Breel Embolo', 'team_id' => 21],
            ['name' => 'Haris Seferovic', 'team_id' => 21],
            ['name' => 'Shani Tarashaj', 'team_id' => 21],
            ['name' => 'Eren Derdiyok', 'team_id' => 21],
            ['name' => 'Volkan Babacan', 'team_id' => 22],
            ['name' => 'Onur Recep Kıvrak', 'team_id' => 22],
            ['name' => 'Harun Tekin', 'team_id' => 22],
            ['name' => 'Hakan Balta', 'team_id' => 22],
            ['name' => 'Semih Kaya', 'team_id' => 22],
            ['name' => 'Ahmet Çalık', 'team_id' => 22],
            ['name' => 'Gökhan Gönül', 'team_id' => 22],
            ['name' => 'Şener Özbayraklı', 'team_id' => 22],
            ['name' => 'Caner Erkin', 'team_id' => 22],
            ['name' => 'İsmail Köybaşı', 'team_id' => 22],
            ['name' => 'Mehmet Topal', 'team_id' => 22],
            ['name' => 'Ozan Tufan', 'team_id' => 22],
            ['name' => 'Selçuk İnan', 'team_id' => 22],
            ['name' => 'Nuri Şahin', 'team_id' => 22],
            ['name' => 'Oğuzhan Özyakup', 'team_id' => 22],
            ['name' => 'Arda Turan', 'team_id' => 22],
            ['name' => 'Yunus Mallı', 'team_id' => 22],
            ['name' => 'Hakan Çalhanoğlu', 'team_id' => 22],
            ['name' => 'Olcay Şahan', 'team_id' => 22],
            ['name' => 'Volkan Şen', 'team_id' => 22],
            ['name' => 'Burak Yılmaz', 'team_id' => 22],
            ['name' => 'Cenk Tosun', 'team_id' => 22],
            ['name' => 'Emre Mor', 'team_id' => 22],
            ['name' => 'Andriy Pyatov', 'team_id' => 23],
            ['name' => 'Denys Boyko', 'team_id' => 23],
            ['name' => 'Mykyta Shevchenko', 'team_id' => 23],
            ['name' => 'Evhen Khacheridi', 'team_id' => 23],
            ['name' => 'Bohdan Butko', 'team_id' => 23],
            ['name' => 'Artem Fedetskyi', 'team_id' => 23],
            ['name' => 'Oleksandr Kucher', 'team_id' => 23],
            ['name' => 'Yaroslav Rakytskiy', 'team_id' => 23],
            ['name' => 'Vyacheslav Shevchuk', 'team_id' => 23],
            ['name' => 'Serhiy Rybalka', 'team_id' => 23],
            ['name' => 'Denys Garmash', 'team_id' => 23],
            ['name' => 'Serhiy Sydorchuk', 'team_id' => 23],
            ['name' => 'Andriy Yarmolenko', 'team_id' => 23],
            ['name' => 'Evhen Konoplyanka', 'team_id' => 23],
            ['name' => 'Oleksandr Karavaev', 'team_id' => 23],
            ['name' => 'Ruslan Rotan', 'team_id' => 23],
            ['name' => 'Taras Stepanenko', 'team_id' => 23],
            ['name' => 'Viktor Kovalenko', 'team_id' => 23],
            ['name' => 'Anatoliy Tymoshchuk', 'team_id' => 23],
            ['name' => 'Oleksandr Zinchenko', 'team_id' => 23],
            ['name' => 'Roman Zozulya', 'team_id' => 23],
            ['name' => 'Pylyp Budkivskyi', 'team_id' => 23],
            ['name' => 'Evhen Seleznyov', 'team_id' => 23],    
        ];

         foreach ($players as $player) {
            DB::table('players')->insert([
                'name' => $player['name'],
                'team_id' => $player['team_id'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s')
            ]);
        }
    }
}
